services:
  crowdsec:
    container_name: crowdsec
    hostname: crowdsec
    image: crowdsecurity/crowdsec:latest
    env_file:
      - .env
    restart: unless-stopped
    environment:
      COLLECTIONS: "crowdsecurity/caddy crowdsecurity/http-cve crowdsecurity/whitelist-good-actors"
      BOUNCER_KEY_CADDY: ${CROWDSEC_API_KEY}
    volumes:
      - ./crowdsec/db:/var/lib/crowdsec/data/
      - ./crowdsec/config:/etc/crowdsec/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - crowdsec
    security_opt:
      - no-new-privileges=true

  dashboard:
    container_name: crowdsec-dashboard
    image: metabase/metabase:latest
    restart: unless-stopped
    user: "0:0"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./dashboard:/metabase-data
      - ./crowdsec/db:/var/lib/crowdsec/data:ro
    networks:
      - crowdsec
      - proxy
    depends_on:
      - crowdsec
    security_opt:
      - no-new-privileges=true
    labels:
      caddy: crowdsec.wsiwiec.com
      caddy.route.reverse_proxy: "{{upstreams 3000}}"

networks:
  crowdsec:
    external: false
    name: crowdsec
  proxy:
    external: true
