services:
  crowdsec:
    container_name: crowdsec
    hostname: crowdsec
    image: crowdsecurity/crowdsec:latest
    env_file:
      - .env
    restart: unless-stopped
    environment:
      COLLECTIONS: "crowdsecurity/caddy crowdsecurity/http-cve crowdsecurity/whitelist-good-actors"
      BOUNCER_KEY_CADDY: ${CROWDSEC_API_KEY}
    volumes:
      - ./crowdsec/db:/var/lib/crowdsec/data/
      - ./crowdsec/config:/etc/crowdsec/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - crowdsec
    security_opt:
      - no-new-privileges=true

  db-viewer:
    container_name: crowdsec-db-viewer
    image: coleifer/sqlite-web
    restart: unless-stopped
    command: -H 0.0.0.0 -x /data/crowdsec.db
    volumes:
      - ./crowdsec/db:/data:ro
    networks:
      - crowdsec
      - proxy
    depends_on:
      - crowdsec
    security_opt:
      - no-new-privileges=true
    labels:
      caddy: crowdsec.wsiwiec.com
      caddy.route.import: crowdsec_auth
      caddy.route.reverse_proxy: "{{upstreams 8080}}"

networks:
  crowdsec:
    external: false
    name: crowdsec
  proxy:
    external: true
