services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      caddy: excalidraw.lab.wsiwiec.com #ðŸ‘ˆ Subdomain using wildcard cert
      caddy.reverse_proxy: "{{upstreams 80}}" #ðŸ‘ˆ Container port

networks:
  proxy:
    external: true
